version: "3"
services:
  postgres_drivenops_db:
    image: postgres
    container_name: postgres_drivenops_db
    restart: always
    ports:
      - 4567:5432
    env_file:
      - ./back-end/.env
    volumes:
      - postgres_drivenops_db:/var/lib/postgresql/data

  node_drivenops_app:
    container_name: node_drivenops_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - postgres_drivenops_db
    env_file:
      - ./back-end/.env

  app_react:
    build: ./front-end
    container_name: app_react
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8020:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - postgres_drivenops_db
      - node_drivenops_app
      - app_react

volumes:
  build_react:
  postgres_drivenops_db:
