version: "3"
services:
  postgres_drivenops_db:
    image: postgres
    container_name: postgres_drivenops_db
    restart: always
    ports:
      - 4567:5432
    env_file:
      - ./back-end/.env.test

  node_drivenops_app:
    container_name: node_drivenops_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - postgres_drivenops_db
    env_file:
      - ./back-end/.env.test
